INSERT INTO labels (label_key, value) VALUES
                                         ('math_basic', 'Math'),
                                         ('sci_intro', 'Science'),
                                         ('eng_grammar', 'English'),
                                         ('hist_world', 'History'),
                                         ('prog_java', 'Java'),
                                         ('prog_js', 'JavaScript'),
                                         ('prog_py', 'Python'),
                                         ('art_draw', 'Drawing'),
                                         ('music_theory', 'Music'),
                                         ('bio_intro', 'Biology'),
                                         ('chem_basic', 'Chemistry'),
                                         ('phys_fund', 'Physics'),
                                         ('geo_world', 'Geography'),
                                         ('lit_classic', 'Literature'),
                                         ('lang_span', 'Spanish'),
                                         ('lang_french', 'French'),
                                         ('lang_germ', 'German'),
                                         ('lang_china', 'Chinese'),
                                         ('lang_japan', 'Japanese'),
                                         ('lang_italy', 'Italian'),
                                         ('comp_basic', 'Computers'),
                                         ('web_html', 'HTML'),
                                         ('web_css', 'CSS'),
                                         ('web_react', 'React'),
                                         ('web_node', 'NodeJS'),
                                         ('db_sql', 'SQL'),
                                         ('db_mongo', 'MongoDB'),
                                         ('soft_skill', 'SoftSkill'),
                                         ('leadership', 'Leader'),
                                         ('teamwork', 'Teamwork'),
                                         ('comm_skill', 'Comm'),
                                         ('prob_solve', 'ProblemSolv'),
                                         ('crit_think', 'CritThink'),
                                         ('creativity', 'Creative'),
                                         ('time_mgmt', 'TimeMgmt'),
                                         ('study_skill', 'Study'),
                                         ('exam_prep', 'ExamPrep'),
                                         ('test_mcq', 'MCQ'),
                                         ('test_essay', 'Essay'),
                                         ('quiz_short', 'Quiz'),
                                         ('project', 'Project'),
                                         ('assign', 'Assign'),
                                         ('homework', 'Homework'),
                                         ('lab_work', 'LabWork'),
                                         ('seminar', 'Seminar'),
                                         ('workshop', 'Workshop'),
                                         ('course_plan', 'Plan'),
                                         ('syllabus', 'Syllabus'),
                                         ('module', 'Module'),
                                         ('unit', 'Unit');


INSERT INTO users (first_name, last_name, email, picture) VALUES
                                                              ('Alice', 'Smith', 'alice.smith@example.com', 'https://picsum.photos/seed/alice/100'),
                                                              ('Bob', 'Johnson', 'bob.johnson@example.com', 'https://picsum.photos/seed/bob/100'),
                                                              ('Carol', 'Williams', 'carol.williams@example.com', 'https://picsum.photos/seed/carol/100'),
                                                              ('David', 'Brown', 'david.brown@example.com', 'https://picsum.photos/seed/david/100'),
                                                              ('Eve', 'Jones', 'eve.jones@example.com', 'https://picsum.photos/seed/eve/100'),
                                                              ('Frank', 'Garcia', 'frank.garcia@example.com', 'https://picsum.photos/seed/frank/100'),
                                                              ('Grace', 'Martinez', 'grace.martinez@example.com', 'https://picsum.photos/seed/grace/100'),
                                                              ('Hank', 'Rodriguez', 'hank.rodriguez@example.com', 'https://picsum.photos/seed/hank/100'),
                                                              ('Ivy', 'Lee', 'ivy.lee@example.com', 'https://picsum.photos/seed/ivy/100'),
                                                              ('Jack', 'Walker', 'jack.walker@example.com', 'https://picsum.photos/seed/jack/100'),
                                                              ('Kathy', 'Hall', 'kathy.hall@example.com', 'https://picsum.photos/seed/kathy/100'),
                                                              ('Leo', 'Allen', 'leo.allen@example.com', 'https://picsum.photos/seed/leo/100'),
                                                              ('Mona', 'Young', 'mona.young@example.com', 'https://picsum.photos/seed/mona/100'),
                                                              ('Nate', 'King', 'nate.king@example.com', 'https://picsum.photos/seed/nate/100'),
                                                              ('Olga', 'Wright', 'olga.wright@example.com', 'https://picsum.photos/seed/olga/100'),
                                                              ('Paul', 'Scott', 'paul.scott@example.com', 'https://picsum.photos/seed/paul/100'),
                                                              ('Quinn', 'Green', 'quinn.green@example.com', 'https://picsum.photos/seed/quinn/100'),
                                                              ('Rita', 'Baker', 'rita.baker@example.com', 'https://picsum.photos/seed/rita/100'),
                                                              ('Sam', 'Adams', 'sam.adams@example.com', 'https://picsum.photos/seed/sam/100'),
                                                              ('Tina', 'Nelson', 'tina.nelson@example.com', 'https://picsum.photos/seed/tina/100');